steps:
- id: 'git-repo-status'
  name: 'alpine'
  entrypoint: 'sh'
  dir: /workspace
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$REPO_NAME"
      echo "$TAG_NAME"
      echo "***********************"

# Go app buildpack
- name: 'gcr.io/cloud-builders/gcloud'
  timeout: 240s
  args: [alpha, builds, submit, 
    --pack, image=us-central1-docker.pkg.dev/mbychkowski-lab/gcp-pipeline/simple-go,
    --tag, $TAG_NAME]
