steps:
- id: 'git-repo-status'
  name: 'alpine'
  entrypoint: 'sh'
  dir: /workspace
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$REPO_NAME"
      echo "$TAG_NAME"
      echo "***********************"

# Go app buildpack
- id: 'run-buildpack'
  name: 'gcr.io/cloud-builders/gcloud'
  timeout: 240s
  args: [alpha, builds, submit, --pack, image=us-central1-docker.pkg.dev/mbychkowski-lab/gcp-pipeline/simple-go:$TAG_NAME]

# Deploy
- id: deploy
  name: 'gcr.io/cloud-builders/gcloud'
  waitFor: 'run-buildpack'
  args: 
  - | 
      gcloud deploy releases create test-release-001 \
        --project=mbychkowski-lab \
        --region=us-central1 \
        --delivery-pipeline=my-gke-demo-app-1 \
        --images=simple-go=us-central1-docker.pkg.dev/mbychkowski-lab/gcp-pipeline/simple-go:$TAG_NAME
